# some default settings for ease of
# access (when developing plugins)
allow-flight=true
enforce-secure-profile=false
level-type=minecraft:flat
online-mode=false
generator-settings={"biome":"minecraft:void","layers":[{"block":"minecraft:bedrock","height":1},{"block":"minecraft:black_concrete","height":62},{"block":"minecraft:tinted_glass","height":1}]}
